// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzWalksApi_Dotnet_8.Data;

#nullable disable

namespace NzWalksApi_Dotnet_8.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20250821154205_Seedinf")]
    partial class Seedinf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NzWalksApi_Dotnet_8.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ee976ef-e1fe-4f41-8913-107a64a1c0f3"),
                            Name = "Eazy"
                        },
                        new
                        {
                            Id = new Guid("0ae912b6-3d6d-4b1f-809a-ea83701543cd"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("6e2596b0-866d-4cb8-a799-12eee0ac2c60"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NzWalksApi_Dotnet_8.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e2596b0-866d-4cb8-a799-12eee0ac2c61"),
                            Code = "AUK",
                            Name = "Auckland",
                            RegionImageUrl = "auckland_image.jpg"
                        },
                        new
                        {
                            Id = new Guid("1e2555b0-666d-4cb8-a449-12eee0ac2c61"),
                            Code = "WGL",
                            Name = "Wellington",
                            RegionImageUrl = "welli.jpg"
                        },
                        new
                        {
                            Id = new Guid("1e2000b0-866d-4cb9-a799-14eee0ac2c61"),
                            Code = "NSL",
                            Name = "Nelson",
                            RegionImageUrl = "nelson_image.jpg"
                        },
                        new
                        {
                            Id = new Guid("1e3456b0-866d-4cb9-a111-14eee0ac2c61"),
                            Code = "STL",
                            Name = "Southland"
                        });
                });

            modelBuilder.Entity("NzWalksApi_Dotnet_8.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NzWalksApi_Dotnet_8.Models.Domain.Walk", b =>
                {
                    b.HasOne("NzWalksApi_Dotnet_8.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NzWalksApi_Dotnet_8.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
